function W_y_F = get_c(in1)
%GET_C
%    W_Y_F = GET_C(IN1)

%    This function was generated by the Symbolic Math Toolbox version 8.6.
%    23-Nov-2022 15:51:40

q1 = in1(2,:);
q2 = in1(3,:);
y = in1(1,:);
t2 = cos(q2);
t3 = sin(q1);
W_y_F = t3.*(2.0./2.5e+1)+y+t3.*(t2.*(2.0./2.5e+1)+2.0./2.5e+1)+cos(q1).*sin(q2).*(4.0./2.5e+1)+t2.*t3.*(2.0./2.5e+1);
