function W_X_B = get_W_X_B(in1)
%GET_W_X_B
%    W_X_B = GET_W_X_B(IN1)

%    This function was generated by the Symbolic Math Toolbox version 8.6.
%    23-Nov-2022 15:51:40

y = in1(1,:);
W_X_B = reshape([1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,y,0.0,1.0],[4,4]);
