function out1 = get_J_v_B
%GET_J_V_B
%    OUT1 = GET_J_V_B

%    This function was generated by the Symbolic Math Toolbox version 8.6.
%    23-Nov-2022 15:51:41

out1 = reshape([0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0],[3,3]);
