function l_rest = get_l_rest
%GET_L_REST
%    L_REST = GET_L_REST

%    This function was generated by the Symbolic Math Toolbox version 8.6.
%    23-Nov-2022 15:51:41

l_rest = sqrt(3.2e+1)./2.5e+1;
