function E_sys = get_E_sys(in1)
%GET_E_SYS
%    E_SYS = GET_E_SYS(IN1)

%    This function was generated by the Symbolic Math Toolbox version 8.6.
%    23-Nov-2022 15:51:41

dq1 = in1(5,:);
dq2 = in1(6,:);
dy = in1(4,:);
q1 = in1(2,:);
q2 = in1(3,:);
y = in1(1,:);
t2 = cos(q1);
t3 = cos(q2);
t4 = sin(q1);
t5 = sin(q2);
t6 = q1+q2;
t7 = cos(t6);
t8 = t3.*(2.0./2.5e+1);
t9 = t2.*1.688e-2;
t10 = t3.*3.968e-4;
t11 = t8+2.0./2.5e+1;
t12 = t7.*2.48e-3;
t13 = t10+1.984e-4;
t14 = t9+t12;
E_sys = t4.*1.655928e-1+y.*3.22749+sin(t6).*2.43288e-2+dy.*(dy.*1.645e-1+dq2.*t7.*1.24e-3+(dq1.*t14)./2.0)+(sqrt(3.2e+1)./2.5e+1-sqrt((t2.*(2.0./2.5e+1)-t4.*t5.*(4.0./2.5e+1)+t2.*t8+t2.*t11).^2+(t4.*(2.0./2.5e+1)+t2.*t5.*(4.0./2.5e+1)+t4.*t8+t4.*t11).^2)).^2.*1.5e+2+dq1.*((dq2.*t13)./2.0+(dy.*t14)./2.0+(dq1.*(t3.*7.936e-4+1.9456e-3))./2.0)+dq2.*(dq2.*3.022958333333333e-4+(dq1.*t13)./2.0+dy.*t7.*1.24e-3);
