function W_X_UL = get_W_X_UL(in1)
%GET_W_X_UL
%    W_X_UL = GET_W_X_UL(IN1)

%    This function was generated by the Symbolic Math Toolbox version 8.6.
%    23-Nov-2022 15:51:40

q1 = in1(2,:);
y = in1(1,:);
t2 = cos(q1);
t3 = sin(q1);
W_X_UL = reshape([t2,t3,0.0,0.0,-t3,t2,0.0,0.0,0.0,0.0,1.0,0.0,t2.*(2.0./2.5e+1),t3.*(2.0./2.5e+1)+y,0.0,1.0],[4,4]);
