function W_X_LL = get_W_X_LL(in1)
%GET_W_X_LL
%    W_X_LL = GET_W_X_LL(IN1)

%    This function was generated by the Symbolic Math Toolbox version 8.6.
%    23-Nov-2022 15:51:40

q1 = in1(2,:);
q2 = in1(3,:);
y = in1(1,:);
t2 = cos(q1);
t3 = cos(q2);
t4 = sin(q1);
t5 = sin(q2);
t6 = t2.*t3;
t7 = t2.*t5;
t8 = t3.*t4;
t9 = t4.*t5;
t11 = t3.*(2.0./2.5e+1);
t10 = -t9;
t12 = t11+2.0./2.5e+1;
t13 = t6+t10;
W_X_LL = reshape([t13,t7+t8,0.0,0.0,-t7-t8,t13,0.0,0.0,0.0,0.0,1.0,0.0,t2.*(2.0./2.5e+1)-t9.*(2.0./2.5e+1)+t2.*t12,t4.*(2.0./2.5e+1)+t7.*(2.0./2.5e+1)+y+t4.*t12,0.0,1.0],[4,4]);
