function r_F_pol = get_r_F_pol(in1)
%GET_R_F_POL
%    R_F_POL = GET_R_F_POL(IN1)

%    This function was generated by the Symbolic Math Toolbox version 8.6.
%    23-Nov-2022 15:51:40

q1 = in1(2,:);
q2 = in1(3,:);
t2 = q1+q2;
r_F_pol = [sqrt(2.0).*sqrt(cos(q2)+1.0).*(4.0./2.5e+1);atan2(sin(q1).*(4.0./2.5e+1)+sin(t2).*(4.0./2.5e+1),cos(q1).*(4.0./2.5e+1)+cos(t2).*(4.0./2.5e+1))];
