function E_sys_d = get_E_sys_d(in1,H_d)
%GET_E_SYS_D
%    E_SYS_D = GET_E_SYS_D(IN1,H_D)

%    This function was generated by the Symbolic Math Toolbox version 8.6.
%    23-Nov-2022 15:51:41

q1 = in1(2,:);
q2 = in1(3,:);
t2 = sin(q1);
E_sys_d = t2.*1.41264e-1+conj(H_d).*3.22749+cos(q1).*sin(q2).*2.43288e-2+sqrt(3.2e+1).*1.290996e-1+t2.*(cos(q2).*(2.0./2.5e+1)+2.0./2.5e+1).*3.0411e-1;
