function out1 = get_J_v_UL(in1)
%GET_J_V_UL
%    OUT1 = GET_J_V_UL(IN1)

%    This function was generated by the Symbolic Math Toolbox version 8.6.
%    23-Nov-2022 15:51:41

q1 = in1(2,:);
out1 = reshape([0.0,1.0,0.0,sin(q1).*(-2.0./2.5e+1),cos(q1).*(2.0./2.5e+1),0.0,0.0,0.0,0.0],[3,3]);
