function foot_pos = get_foot_pos(in1)
%GET_FOOT_POS
%    FOOT_POS = GET_FOOT_POS(IN1)

%    This function was generated by the Symbolic Math Toolbox version 8.6.
%    23-Nov-2022 15:51:40

q1 = in1(2,:);
q2 = in1(3,:);
t2 = cos(q1);
t3 = cos(q2);
t4 = sin(q1);
t5 = sin(q2);
t6 = t3.*(2.0./2.5e+1);
t7 = t6+2.0./2.5e+1;
foot_pos = [t2.*(2.0./2.5e+1)+t2.*t6+t2.*t7-t4.*t5.*(4.0./2.5e+1);t4.*(2.0./2.5e+1)+t2.*t5.*(4.0./2.5e+1)+t4.*t6+t4.*t7];
